Hello Microvers Project Pull Request
mrkamin/Hello-Microverse pull request #1
Opened 2022-09-21 02:48 UTC by mrkamin

2022-09-21 05:26 UTC, Bondok6 requested changes
## Hi @mrkamin 🙋‍♂️, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

<img src="https://media0.giphy.com/media/31Q36EHJ7C5ZoIMw79/giphy.gif"/>

## Highlights
- No Linter errors ✅
- Correct GitHub flow ✅
- Your repo is professional ✅


## Required Changes ♻️

- [x] Your `README` file should be descriptive - all main headers from the [README template](https://github.com/microverseinc/readme-template/blob/master/README.md) should be present 👌
Kindly, update it 💯

![image](https://user-images.githubusercontent.com/45231276/191420737-f7a095b9-96df-44d3-81e0-84c4626199a7.png)

- [x] _Check the comments under the review._ ⬇

## Optional suggestions

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-21 05:26 UTC, Bondok6 commented on style.css
> +}
- [ ] Great job here 👌💯 but according to the requirements, you should use a **class** to select the `<h1>` tag, So Kindly add a class name to this element `<h1 class="header">` in your HTML and use it in your CSS file 
`.header {color: aqua;}`👌


![image](https://user-images.githubusercontent.com/45231276/185032956-ca65df88-2c93-4fdc-97c0-93e7050d2989.png)

2022-09-21 05:26 UTC, Bondok6 commented on index.html
> +    <title>Document</title>
- [OPTIONAL] I think it would be better to use a descriptive title 💡

2022-09-22 17:05 UTC, Felix45 requested changes
Hi @mrkamin , 

Great work on making the changes requested by a previous reviewer 👏 

You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

 ## Highlights :heavy_check_mark: 
- No linter errors :white_check_mark: 
- Correct Github flow :white_check_mark: 
- Your repo is professional :white_check_mark: 


 ## Required Changes ♻️
_Check the comments under the review._
- [ ] As mentioned by the previous reviewer, please consider updating your readme to be more descriptive and professional, you can use this [>> readme template](https://github.com/microverseinc/readme-template/blob/master/README.md) from Microverse. A good readme file should be professional and descriptive of the project, for people viewing your repository. Please try as much as possible to fill all sections of the readme file.

Current readme
![Screenshot from 2022-09-22 19-50-32](https://user-images.githubusercontent.com/16392046/191806207-4679abb1-67b7-417a-b835-b8c6383ce7f1.png)


## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-22 17:05 UTC, Felix45 commented on style.css
> +}
As mentioned by the previous reviewer please consider using a `class selector` to select the `h1` tag, as described in the project requirements shown below :point_down:  this is a requirement for this project.

![Screenshot from 2022-09-22 19-55-52](https://user-images.githubusercontent.com/16392046/191808100-0d0d0bbd-5eec-48b4-8b1f-16c42084ac34.png)

You can do this as shown below
#### index.html
```HTML
<h1 class="header"> Hello Microverse </h1>
```
#### style.css
```CSS
.header { color: aqua; }
```

2022-09-23 08:19 UTC, merged

2022-09-23 09:27 UTC, roshan-bajgain reviewed
Hi @mrkamin, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Highlights
- No linter errors. ✔️
- GitHub flow is followed. ✔️

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-23 09:27 UTC, roshan-bajgain commented on style.css
> +}
- [ ] As requested by the previous reviewer please use the class on the `h1` tag and give style. ie:
`<h1 class="header"> Hello Microverse </h1>`
`header { color: aqua; }`